export const PREFIX = 'POSTS_'; //remove it
export const FETCH_ERROR = PREFIX + 'FETCH_ERROR';
export const FETCH_START = PREFIX + 'FETCH_START';
export const FETCH_SUCCESS = PREFIX + 'FETCH_SUCCESS';
export const FETCH_SINGLE_POST_SUCCESS = PREFIX + 'FETCH_SINGLE_POST_SUCCESS';


//USER
export const USER_LOGIN_SUCCESSFULL = 'USER_LOGIN_SUCCESSFULL'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'
export const USER_LOGIN_START = 'USER_LOGIN_START'
export const SET_USER = 'SET_USER'
